### PR TITLE
fix: setuptools_scm missing

### PR DESCRIPTION
**Pull request by henryiii**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* Reset the build number to `0` (if the version changed)
* [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* Ensured the license file is being packaged.

Manually pushed to fork this time, instead of expecting `gh` to ask, which either it didn't or I bypassed the question out of habit (quite possible).

See https://github.com/conda-forge/scikit-hep-feedstock/pull/18.

### CODE REVIEW

**Review by eduardo-rodrigues — APPROVED** [review]
Thank you @henryiii 👍.

For my knowledge, what will happen since you changed the build number but not the version? Do all 1.6.0 conda dist files get replaced at https://anaconda.org/conda-forge/resample/files?

**Comment by henryiii** [comment]
You'll get 1.6.0_1 instead of 1.6.0_0 once this goes in.

**Comment by henryiii** [comment]
(And after it builds & uploads)

**Comment by henryiii** [comment]
Though for some reason I'm already seeing some `_1` files there, maybe they are uploaded by the PR and then marked usable when this is merged?

**Comment by eduardo-rodrigues** [comment]
Interesting!

I approved and if you @HDembinski approve and merge I should be able to move forward with scikit-hep :). Thank you.

**Review by HDembinski — APPROVED** [review]

**Comment by HDembinski** [comment]
Thank you for the help.

**Pull request merged**
